### ISSUE TITLE
Errors when running the demo app

### ISSUE THREAD

**Issue by Lucas-Pino** [RenaudLN/dmc-transferlist-aio#1]
I get the following errors when i run the demo app.
<img width="718" alt="Screenshot 2024-07-04 at 4 49 06 PM" src="https://github.com/RenaudLN/dmc-transferlist-aio/assets/53064450/c3d30522-d715-48bf-9a6f-3afd28818f99">

**Comment by RenaudLN** [comment]
This is an issue with DMC 0.14, check the migration guide, you need to use react 18.

**Comment by Lucas-Pino** [comment]
thank you!, yes it was my mistake for not reading the migration guide.

Do you happen to know what might be causing the following errors?
they don't hinder any functionality of my app but they only appeared when i migrated from dmc 0.12 to 0.14 and replaced the transfeList with the transferlist_aio component
any help is appreciated.
<img width="592" alt="Screenshot 2024-07-09 at 10 11 57 PM" src="https://github.com/RenaudLN/dmc-transferlist-aio/assets/53064450/243ea502-764c-4069-91d6-d383f3ca4f27">
